#!/usr/bin/env bash
# Configre Nginx to listen on port 80

# remove default Nginx configuration file
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restarting nginx
service nginx restart
