#!/usr/bin/env bash
# configuring a Nginx server to listen to port 80

# create symbolic link btwn nginx config file and enabled site directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restarting nginx
service nginx start
# Terminating the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
