#!/usr/bin/env bash
# Displays a list of all the currently running processes.
# Display user oriented format and hierachy.
#   Shows all processes, for all users, including those
#+  which might not have a TTY.

ps -auxf
