#!/usr/bin/env bash
# Displays "Best School" 10 times using the while loop.
#   But displays "Hi" before "Best School" on the 9th iteration.

counter=0

while [ $counter -lt 10 ]
do
  if [ $counter -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( counter++ ))
done
