#!/usr/bin/env bash
# Displays the contents of the current directory in the list format.
#   Only displaying the part of the name after the first dash. 

list=$(ls)
for item in $list; do
  echo "$item" | cut -d '-' -f2
done
